### PR TITLE
Issue #223 structured test output

### LINKED ISSUE #223: Reify failed examples and display them accordingly
The error output from most runners (except from Gobstones :smirk:) is very rough to a student: tempfile paths, test framework language, etc.

Runners should be able to return structured data instead of string, configurable on a per language basis. This data should be a JSON and could consist of:
- a `global_status`, with possible values `failed|passed`
- an array of `examples`, with:
  + a `title`, in sentence case
  + a `status`, with possible values `failed|passed`
  + an `output`, with the content-type defined for the language

<s>To make this change backward compatible, a language should be able to opt-in by setting a flag "Returns structured data?"</s>

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #223

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Test results are being displayed this way:

testresults1

**Comment by flbulgarelli** [comment]
With a few css changes, we could make it look like this: 

testresults2

Which one do you prefer?

**Comment by fedescarpa** [comment]
I like the best of both worlds. Is it possible to have the red line with
the grey background?

**Comment by faloi** [comment]
The colored titles are great, but I don't like the callout.

Other thoughts:
- I think we should sort the tests, based on their status
- what about collapsing the error output?

**Comment by flbulgarelli** [comment]
I don't like sorting based on status, since we are breaking the order the exercise creator designed - we should assume she had a good reasong for put test in the given order.

On the other hand, I like the idea of collapsing error output. With that in mind, the style of code get not really important.

File: app/controllers/submissions_controller.rb [hunk 1]
```diff
@@ -1,4 +1,4 @@
-class SubmissionsController < ApplicationController
+class SubmissionsController < ApplicationController #FIXME remove
```
Comment (faloi) [inline app/controllers/submissions_controller.rb]: Are you gonna solve this now?

File: app/helpers/application_helper.rb [hunk 2]
```diff
@@ -1,4 +1,5 @@
 module ApplicationHelper
+  #FIXME only include what is needed
```
Comment (faloi) [inline app/helpers/application_helper.rb]: Are you gonna solve this now?

File: app/helpers/concerns/test_results_rendering.rb [hunk 3]
```diff
@@ -0,0 +1,9 @@
+module TestResultsRendering
+  def render_test_results(submission)
+    if submission.test_results.present?
+      render partial: 'layouts/test_results', locals: {test_results: submission.test_results, output_content_type: submission.output_content_type}
```
Comment (faloi) [inline app/helpers/concerns/test_results_rendering.rb]: Can't you directly pass the submission? Or it must be a hash?

File: app/models/concerns/with_status.rb [hunk 4]
```diff
@@ -2,7 +2,7 @@ module WithStatus
   extend ActiveSupport::Concern
 
   included do
-    enum status: [:pending, :running, :passed, :failed]
+    enum status: [:pending, :running, :passed, :failed, :errored, :aborted, :passed_with_warnings]
```
Comment (faloi) [inline app/models/concerns/with_status.rb]: Can we turn this into something that support adding logic? There are many places where you are switching, perhaps it would be nicer to delegate that behaviour to the statuses.

File: app/helpers/concerns/test_results_rendering.rb (hunk 3 above)
Comment (flbulgarelli) [inline app/helpers/concerns/test_results_rendering.rb]: It must be a hash

File: app/models/concerns/with_status.rb (hunk 4 above)
Comment (flbulgarelli) [inline app/models/concerns/with_status.rb]: Yeah, I think so. We should change to something like `classy_enum`, but that means changing some DB thinks - yeah, awful, I know. Would you open an issue?

Comment (faloi) [inline app/models/concerns/with_status.rb]: https://github.com/mumuki/mumuki-platform/issues/248

**Comment by flbulgarelli** [comment]
Removed FIXMEs here  2e60081ff77adbe59aeeb169156c5ef123efbb42 and here edf2a1712d0ebbfee38e4897b78a421f3d2e4306
